<?php
/*----------------- php source file -----------------
  @file      : assets/lib/de_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [27.06.2016 17:18:29] -->
  ------HoC------
 ----------------------------------------------------*/

$top_bar_lang_en = "Englisch";
$top_bar_lang_de = "Deutsch";
$top_bar_lang_hu = "Ungarisch";

$top_bar_contact = "Kontakt";
$top_bar_welcome = "Willkommen im TSVÖ Portal";
$top_bar_account = "Mein Konto";
$top_bar_profile = "Mein Profil";
$top_bar_logout = "Ausloggen";
$top_bar_login = "Anmeldung";
$top_bar_competition = "Meine Veranstaltungen";

$footer["copyright"] = "Alle Rechte vorbehalten";

$contact["header"] = "Schreiben Sie uns ein paar Zeilen oder sagen Sie nur, <strong><em>Hallo!</em></strong>";
$contact["fullname"] = "vollständiger Name";
$contact["email"] = "E-mail Addresse";
$contact["phone"] = "Telefon";
$contact["subject"] = "Thema";
$contact["divisional"] = "Bereich";
$contact["message"] = "Nachricht";
$contact["file"] = "Dateianhang";
$contact["send"] = "NACHRICHT SENDEN";
$contact["select"] = "Wähle eine Datei";
$contact["maxfilesize"] = "Max. Dateigröße";
$contact["successfull"] = "<strong>Danke!</strong> Ihre Nachricht wurde erfolgreich gesendet!";
$contact["error"] = "<strong>[SMTP] Fehler!</strong> Interner Serverfehler!";
$contact["sorry"] = "<strong>Sorry!</strong> Sie müssen alle Pflichtfelder (*) Felder ausfüllen!";


?>