<?php
/*----------------- php source file -----------------
  @file      : assets/lib/de_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [26.06.2016 13:27:51] -->
  ------HoC------
 ----------------------------------------------------*/

$top_bar_lang_en = "Englisch";
$top_bar_lang_de = "Deutsch";
$top_bar_lang_hu = "Ungarisch";

$top_bar_contact = "Kontakt";
$top_bar_welcome = "Willkommen im TSVÖ Portal";
$top_bar_account = "Mein Konto";
$top_bar_profile = "Mein Profil";
$top_bar_logout = "Ausloggen";
$top_bar_login = "Anmeldung";
$top_bar_competition = "Meine Veranstaltungen";
?>