<?php
/*----------------- php source file -----------------
  @file      : assets/lib/de_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [30.06.2016 10:21:26] -->
  ------HoC------
 ----------------------------------------------------*/

$secure["header"] = "Anmeldung/Registrieren";
$secure["return_user"] = "Ich bin bereits User";
$secure["login_false"] = "Login falsch!";
$secure["user_info"] = "Erforderlich zum Anmelden";
$secure["pass_info"] = "Passwort eingeben";
$secure["forgot_pw"] = "Passwort vergessen";
$secure["login"] = "Anmelden";
$secure["no_account"] = "Sie haben noch kein Konto?";
$secure["pw_failure"] = "Passwort stimmt nicht überein";


$top_bar["lang_en"] = "Englisch";
$top_bar["lang_de"] = "Deutsch";
$top_bar["lang_hu"] = "Ungarisch";
$top_bar["contact"] = "Kontakt";
$top_bar["welcome"] = "Willkommen im TSVÖ Portal";
$top_bar["account"] = "Mein Konto";
$top_bar["profile"] = "Mein Profil";
$top_bar["logout"] = "Ausloggen";
$top_bar["login"] = "Anmelden";
$top_bar["competition"] = "Meine Veranstaltungen";
$top_bar["register"] = "Registrieren";

$footer["copyright"] = "Alle Rechte vorbehalten";
$footer["subscribe"] = "Abonnieren Sie unseren Newsletter um wichtige Neuigkeiten zu erhalten";
$footer["sub_succsess"] = "Angemeldet! Vielen Dank!";
$footer["sub_email"] = "Geben sie ihre E-Mail Adresse ein";
$footer["sub_send"] = "Anmelden";
$footer["explore"] = "erkunde die Webseite";

$contact["header"] = "Schreiben Sie uns ein paar Zeilen oder sagen Sie nur, <strong><em>Hallo!</em></strong>";
$contact["fullname"] = "vollständiger Name";
$contact["email"] = "E-mail Addresse";
$contact["phone"] = "Telefon";
$contact["subject"] = "Thema";
$contact["divisional"] = "Bereich";
$contact["message"] = "Nachricht";
$contact["file"] = "Dateianhang";
$contact["send"] = "NACHRICHT SENDEN";
$contact["select"] = "Wähle eine Datei";
$contact["maxfilesize"] = "Max. Dateigröße";
$contact["successfull"] = "<strong>Danke!</strong> Ihre Nachricht wurde erfolgreich gesendet!";
$contact["error"] = "<strong>[SMTP] Fehler!</strong> Interner Serverfehler!";
$contact["sorry"] = "<strong>Sorry!</strong> Sie müssen alle Pflichtfelder (*) Felder ausfüllen!";


?>