<?php
/*----------------- php source file -----------------
  @file      : assets/lib/en_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [27.06.2016 17:18:29] -->
  ------HoC------
 ----------------------------------------------------*/

$top_bar_lang_en = "English";
$top_bar_lang_de = "German";
$top_bar_lang_hu = "Hungarian";

$top_bar_contact = "contact";
$top_bar_welcome = "Welcome to TSVOe Portal";
$top_bar_account = "My Account";
$top_bar_profile = "My Profile";
$top_bar_logout = "Logout";
$top_bar_login = "Login";
$top_bar_competition = "My event";

$footer["copyright"] = "All Rights Reserved";

$contact["header"] = "Write us a line or just say <strong><em>Hello!</em></strong>";
$contact["fullname"] = "Full Name";
$contact["email"] = "E-mail Address";
$contact["phone"] = "Phone";
$contact["subject"] = "Subject";
$contact["divisional"] = "Divisional";
$contact["message"] = "Message";
$contact["file"] = "File Attachment";
$contact["send"] = "SEND MESSAGE";
$contact["select"] = "Select a File";
$contact["maxfilesize"] = "Max. File size";
$contact["successfull"] = "<strong>Thank You!</strong> Your message successfully sent!";
$contact["error"] = "<strong>[SMTP] Error!</strong> Internal server error!";
$contact["sorry"] = "<strong>Sorry!</strong> You need to complete all mandatory (*) fields!";


?>