<?php
/*----------------- php source file -----------------
  @file      : assets/lib/en_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [26.06.2016 13:27:51] -->
  ------HoC------
 ----------------------------------------------------*/

$top_bar_lang_en = "English";
$top_bar_lang_de = "German";
$top_bar_lang_hu = "Hungarian";

$top_bar_contact = "contact";
$top_bar_welcome = "Welcome to TSVOe Portal";
$top_bar_account = "My Account";
$top_bar_profile = "My Profile";
$top_bar_logout = "Logout";
$top_bar_login = "Login";
$top_bar_competition = "My event";
?>