<?php
/*----------------- php source file -----------------
  @file      : assets/lib/en_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [29.06.2016 16:42:51] -->
  ------HoC------
 ----------------------------------------------------*/

$secure["header"] = "Login/Register";
$secure["return_user"] = "I'm a returning user";
$secure["login_false"] = "Login Incorrect!";
$secure["email_info"] = "Needed to verify your account";
$secure["pass_info"] = "Type your account password";
$secure["forgot_pw"] = "Forgot Password";
$secure["login"] = "Login";
$secure["no_account"] = "Don't have an account yet?";
$secure["pw_failure"] = "Password do not match";


$top_bar["lang_en"] = "English";
$top_bar["lang_de"] = "German";
$top_bar["lang_hu"] = "Hungarian";
$top_bar["contact"] = "contact";
$top_bar["welcome"] = "Welcome to TSVOe Portal";
$top_bar["account"] = "My Account";
$top_bar["profile"] = "My Profile";
$top_bar["logout"] = "Logout";
$top_bar["login"] = "Login";
$top_bar["competition"] = "My event";
$top_bar["register"] = "Register";

$footer["copyright"] = "All Rights Reserved";
$footer["subscribe"] = "Subscribe to Our Newsletter to get Important News";
$footer["sub_succsess"] = "Subscribed! Thank you!";
$footer["sub_email"] = "Enter your Email";
$footer["sub_send"] = "Subscribe";
$footer["explore"] = "EXPLORE the WEBSITE";

$contact["header"] = "Write us a line or just say <strong><em>Hello!</em></strong>";
$contact["fullname"] = "Full Name";
$contact["email"] = "E-mail Address";
$contact["phone"] = "Phone";
$contact["subject"] = "Subject";
$contact["divisional"] = "Divisional";
$contact["message"] = "Message";
$contact["file"] = "File Attachment";
$contact["send"] = "SEND MESSAGE";
$contact["select"] = "Select a File";
$contact["maxfilesize"] = "Max. File size";
$contact["successfull"] = "<strong>Thank You!</strong> Your message successfully sent!";
$contact["error"] = "<strong>[SMTP] Error!</strong> Internal server error!";
$contact["sorry"] = "<strong>Sorry!</strong> You need to complete all mandatory (*) fields!";


?>