<?php
/*----------------- php source file -----------------
  @file      : assets/lib/hu_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [27.06.2016 09:36:01] -->
  ------HoC------
 ----------------------------------------------------*/

$top_bar_lang_en = "Angol";
$top_bar_lang_de = "Német";
$top_bar_lang_hu = "Magar";

$top_bar_contact = "Érintkezés";
$top_bar_welcome = "Üdvözöljük TSVOe Portál";
$top_bar_account = "A fiókom";
$top_bar_profile = "A profilom";
$top_bar_logout = "Kijelentkezés";
$top_bar_login = "Belépek";
$top_bar_competition = "Saját esemény";

$contact["header"] = "Írjon nekünk egy sort, vagy csak köszönni";
$contact["fullname"] = "Teljes név";
$contact["email"] = "Email cím";
$contact["phone"] = "Telefon";
$contact["subject"] = "Tantárgy";
$contact["divisional"] = "Terület";
$contact["message"] = "Üzenet";
$contact["file"] = "Csatolt fájl";
$contact["send"] = "ÜZENET KÜLDÉSE";
$contact["select"] = "Válasszon ki egy fájlt";
$contact["maxfilesize"] = "Max. Fájl méret";
$contact["successfull"] = "<strong>Köszönöm!</strong> Az üzenet sikeresen elküldve!";
$contact["error"] = "<strong>[SMTP] Hiba!</strong> Belső Szerverhiba!";
$contact["sorry"] = "<strong>Sajnálom!</strong> Be kell, hogy töltse ki az összes kötelező (*) mezők!";


?>