<?php
/*----------------- php source file -----------------
  @file      : assets/lib/hu_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [29.06.2016 16:42:51] -->
  ------HoC------
 ----------------------------------------------------*/

$secure["header"] = "Belépek/Regisztráció";
$secure["return_user"] = "Én egy visszatérő felhasználó";
$secure["login_false"] = "Helytelen bejelentkezés!";
$secure["email_info"] = "Ellenőrzéséhez szükséges fiókjába";
$secure["pass_info"] = "Írja be a fiók jelszavát";
$secure["forgot_pw"] = "Elfelejtett jelszó";
$secure["login"] = "Belépek";
$secure["no_account"] = "Nincs még egy fiókot?";
$secure["pw_failure"] = "A jelszó nem egyezik";


$top_bar["lang_en"] = "Angol";
$top_bar["lang_de"] = "Német";
$top_bar["lang_hu"] = "Magar";
$top_bar["contact"] = "Érintkezés";
$top_bar["welcome"] = "Üdvözöljük TSVOe Portál";
$top_bar["account"] = "A fiókom";
$top_bar["profile"] = "A profilom";
$top_bar["logout"] = "Kijelentkezés";
$top_bar["login"] = "Belépek";
$top_bar["competition"] = "Saját esemény ";
$top_bar["register"] = "Regisztráció";

$footer["copyright"] = "Minden jog fenntartva";
$footer["subscribe"] = "Iratkozzon fel hírlevelünkre, hogy fontos hírek";
$footer["sub_succsess"] = "Jegyzett! Köszönöm!";
$footer["sub_email"] = "Írd be az email címed";
$footer["sub_send"] = "Iratkozz fel";
$footer["explore"] = "ellenőrizze a honlapon";

$contact["header"] = "Írjon nekünk egy sort, vagy csak köszönni";
$contact["fullname"] = "Teljes név";
$contact["email"] = "Email cím";
$contact["phone"] = "Telefon";
$contact["subject"] = "Tantárgy";
$contact["divisional"] = "Terület";
$contact["message"] = "Üzenet";
$contact["file"] = "Csatolt fájl";
$contact["send"] = "ÜZENET KÜLDÉSE";
$contact["select"] = "Válasszon ki egy fájlt";
$contact["maxfilesize"] = "Max. Fájl méret";
$contact["successfull"] = "<strong>Köszönöm!</strong> Az üzenet sikeresen elküldve!";
$contact["error"] = "<strong>[SMTP] Hiba!</strong> Belső Szerverhiba!";
$contact["sorry"] = "<strong>Sajnálom!</strong> Be kell, hogy töltse ki az összes kötelező (*) mezők!";


?>