<?php
/*----------------- php source file -----------------
  @file      : assets/lib/hu_lang.inc
  belongs to : mysql DB
  contact    : Andreas Steiner   (astone@stoneship.at)
  @copyright 2016
  <!-- phpDesigner :: Timestamp [26.06.2016 13:27:51] -->
  ------HoC------
 ----------------------------------------------------*/

$top_bar_lang_en = "Angol";
$top_bar_lang_de = "Német";
$top_bar_lang_hu = "Magar";

$top_bar_contact = "Érintkezés";
$top_bar_welcome = "Üdvözöljük TSVOe Portál";
$top_bar_account = "A fiókom";
$top_bar_profile = "A profilom";
$top_bar_logout = "Kijelentkezés";
$top_bar_login = "Belépek";
$top_bar_competition = "Saját esemény";

?>